 CREATE TABLE `articulos`(
`CODIGO` INT(11) NOT NULL AUTO_INCREMENT,
`NOMBRE` VARCHAR(100) NOT NULL,
`PRECIO` DECIMAL(10,2) NOT NULL,
`FABRICANTE` INT(11) NOT NULL,
PRIMARY KEY (`CODIGO`),
INDEX `FK_FABRICANTE` (`FABRICANTE`),
CONSTRAINT `FK_FABRICANTE` FOREIGN KEY (`FABRICANTE`) REFERENCES `fabricantes` (`CODIGO`)
)
COLLATE='latin1_swedish_ci'
ENGINE=INNODB
;