CREATE TABLE `cajas` (
`NUMEREFERENCIA` INT(11) NOT NULL AUTO_INCREMENT,
`CONTENIDO` VARCHAR(100) NOT NULL,
`VALOR` INT(11) NOT NULL,
`ALMACEN` INT(11) NOT NULL,
PRIMARY KEY (`NUMEREFERENCIA`),
INDEX `FK1_ALMACEN` (`ALMACEN`),
CONSTRAINT `FK1_ALMACEN` FOREIGN KEY (`ALMACEN`) REFERENCES `almacenes` (`codigo`)
)
COLLATE='latin1_swedish_ci'
ENGINE=INNODB
; 